### PR TITLE
fix(cycle-sequences): user defined Cycle Sequences index should begin at 1

### LINKED ISSUE #267: Fix numbering of sequences and make it less able to bring down form preview
Sequence numbering depends upon 0-based number: 

0,1,2

instead of 

1,2,3

which is not intuitive for most users. We should change this in the code to accept 1-based numbering.

Change the calc of items to enable 1-based orders, so you can use 1,2,3 instead of 0,1,2

in tangy-form-reducer:
```js
      currentSequence.forEach((e)=>tempItems.push(newState.items[e]))
// modify to 
      currentSequence.forEach((e)=>tempItems.push(newState.items[e-1]))
```

Also should modify the instruction to illustrate this scheme.

### PR DESCRIPTION
**Pull request by evansdianga**
Users should define cycle sequences beginning from index 1 and not 0

Fixes #267

### CODE REVIEW

File: tangy-form-reducer.js [hunk 1]
```diff
@@ -19,7 +19,7 @@ const tangyFormReducer = function (state = initialState, action) {
       let {cycleSequences} = action.response.form;
       const lastCycleIndex = `${action.response.form.id}-lastCycleIndex`
       const cycleSequencesArray = cycleSequences && cycleSequences.split('\n').map(e=>e.trim())
-      let currentSequence = [...Array(action.response.items.length).keys()]
+      let currentSequence = [...Array(action.response.items.length).fill().map((_, i) => i+1)]
```
Comment (chrisekelley) [inline tangy-form-reducer.js:22]: perrrrrfect!

**Review by chrisekelley — APPROVED** [review]

**Comment by TSSlade** [comment]
@chrisekelley or @evansdianga - does the cycle sequence that applied for a given observation make it into the CSV output? (I know you can infer the sequence from section-level start/open timestamps, but it would be lovely if there were an actual variable that contained the applicable sequence.) If so, what is the varname?
